### PR TITLE
Fixes #130, copes with empty quick links. Plus refactoring for clarity.

### LINKED ISSUE #130: memorial homepage error handling (drupal)
**Frontend or Backend**:  Backend

**Description**
In the memorial takeover editor screen if a quick links biock is on screen but no data in the homepage will return a 500 error even if the memorial theme is turned off.

**How to reproduce**
Save the memorial takeover page with this at the bottom
image

**Additional context**
Error is in: northants/backend/src/modules/nc_system/src/Entity/Node/Homepage.php
in the foreach block at line 203 need to check if the linkData and linkobj are not null before running the rest of the code in the foreach loop

### PR DESCRIPTION
**Pull request by DamienBurkeWN**
Got a bit too keen on this one possibly... I think the various resolveGraphQLFieldToValue functions are in the early stages of becoming unmanageable so most of this PR is a refactor to move the various discrete bits of field related logic out of the function and into separate functions, whilst moving away from repeated if statements to a switch statement. Unfortunately this enlarges the test surface...

### Testing
1. First of all verify that you can view a selection of service landing pages, service pages, news articles, etc. with no changes or errors compared to the prepared_backend branch, as the refactoring has affected all these types of content.
2. Verify that the home page has also not changed.
3. In the memorial config, add an empty quick link and refresh the home page, verify that there is no effect (preprod_backend, by contrast, will error).
4. In the memorial config, set everything up - memorial theme turned on, condolence link, summary, icon, news links, quick links, etc. and verify that the homepage displays correctly in memorial mode.

### CODE REVIEW

File: backend/src/modules/nc_system/src/Entity/Node/Article.php [hunk 1]
```diff
@@ -6,139 +6,146 @@
...
-    return $featuredImageCaption ? $featuredImageCaption->getString() : NULL;
+    return $featuredImageCaption ? $featuredImageCaption->getString() : null;
   }
 
-  /**
-   * {@inheritdoc}
-   */
-  public function resolveGraphQLFieldToValue(string $fieldName) {
-    if ($fieldName === "body") {
-      $body = $this->getBody();
```
Comment (DamienBurkeWN) [inline backend/src/modules/nc_system/src/Entity/Node/Article.php:64]: This chunk of logic moved out into a getBodyResolved() function.

File: backend/src/modules/nc_system/src/Entity/Node/Article.php [hunk 2]
```diff
@@ -6,139 +6,146 @@
...
-    if ($fieldName === "imageAltText"){
-      $image = $this->getImage();
-      if ($image) {
-        return GraphQLFieldResolver::resolveMediaImage($image[0])['altText'];
-      }
-      return NULL;
+    return null;
+  }
+
+  public function getSizedImageURL($width, $height)
```
Comment (DamienBurkeWN) [inline backend/src/modules/nc_system/src/Entity/Node/Article.php:76]: New function to DRY up some of the logic formerly in the resolveGraphQLFieldToValue function.

File: backend/src/modules/nc_system/src/Entity/Node/Article.php [hunk 3]
```diff
@@ -6,139 +6,146 @@
...
     }
-    if ($fieldName === "featuredImageCaption") {
-      return $this->getImageCaption();
+    return null;
+  }
+
+  /**
+   * {@inheritdoc}
+   */
+  public function resolveGraphQLFieldToValue(string $fieldName)
```
Comment (DamienBurkeWN) [inline backend/src/modules/nc_system/src/Entity/Node/Article.php:97]: Refactored as mentioned previously, easier to grok and maintain.

File: backend/src/modules/nc_system/src/Entity/Node/Homepage.php [hunk 4]
```diff
@@ -1,92 +1,166 @@
...
 
-  public function getPromotedLinks(): array {
+  public function getPromotedLinks(): array
+  {
     $promoLinks = [];
     $promoLinksField = $this->field_homepage_hero_links;
     foreach ($promoLinksField as $link) {
-      $test = $this->getLink($link);
-      array_push($promoLinks, $test);
+      $promolinks[] = $this->getLink($link);
```
Comment (DamienBurkeWN) [inline backend/src/modules/nc_system/src/Entity/Node/Homepage.php:36]: A general change to using [] rather than array_push, saves the function call overhead and I think also clearer to read

File: backend/src/modules/nc_system/src/Entity/Node/Homepage.php [hunk 5]
```diff
@@ -1,92 +1,166 @@
...
     }
     return $promoLinks;
   }
 
-  public function getHeroImages(): array {
-    $heroImagesField = $this->get('field_homepage_hero_images')->getValue();
-    return $heroImagesField;
+  public function getPromotedLinksResolved(): array
```
Comment (DamienBurkeWN) [inline backend/src/modules/nc_system/src/Entity/Node/Homepage.php:41]: New function to move out logic formerly in the resolveGraphQLFieldToValue function.

File: backend/src/modules/nc_system/src/Entity/Node/Homepage.php [hunk 6]
```diff
@@ -1,92 +1,166 @@
...
+
+  public function getMemorialImages(): array
+  {
     $config = config_pages_config('memorial_takeover');
-    $memorialImagesField = $config ? $config->get('field_memorial_images')->getValue() : [];
-    return $memorialImagesField;
+    return $config ? $config->get('field_memorial_images')->getValue() : [];
+  }
+
+  public function getMemorialImagesResolved(): array
```
Comment (DamienBurkeWN) [inline backend/src/modules/nc_system/src/Entity/Node/Homepage.php:85]: New function to move out logic formerly in the resolveGraphQLFieldToValue function.

File: backend/src/modules/nc_system/src/Entity/Node/Homepage.php [hunk 7]
```diff
@@ -1,92 +1,166 @@
...
-  public function getMemorialIcon(): array {
+  public function getMemorialIcon(): array
+  {
     $config = config_pages_config('memorial_takeover');
-    $memorialIconField = $config ? $config->get('field_memorial_icon')->getValue() : [];
-    return $memorialIconField;
+    return $config ? $config->get('field_memorial_icon')->getValue() : [];
+  }
+
+  public function getMemorialIconValue()
```
Comment (DamienBurkeWN) [inline backend/src/modules/nc_system/src/Entity/Node/Homepage.php:141]: New function to move out logic formerly in the resolveGraphQLFieldToValue function.

**Review by AnthonyTaylor — APPROVED** [review]
